job_name: job101
cpu_num: 16
memory_size: 16
image_name: qinjielin/python3.6:v0.4
entry_cmd:
- python
- /root/work_ws/example/example1.py
vcpu_num: 1
mount_config:
- efs_name: code_efs
  efs_path: /user3/
  container_path: /root/work_ws
