#============== aws config ==============
cluster_name: example_cluster
aws_access_key_id: xxxx
aws_secret_access_key: xxxxx
region_name: us-east-1

#============== cluster config ==============
execute_gateway: True
efs_names: ["gateway_efs", "model_efs", "data_efs"]
instance_config:
  [
      {
        class: gateway,  #open public dns
        name: gateway,
        type: t2.xlarge,
        num: 1,
        ami_id: ami-0b0ea68c435eb488d, 
        mount_config: [
          {
            efs_name: gateway_efs,
            mount_path: /home/ubuntu/efs/gateway_ws
          },
        ]
      },
      {
        class: user, # dns only access to vpc subnet, not access to outnet
        name: developer,
        type: t2.xlarge,
        num: 2,
        ami_id: ami-0b0ea68c435eb488d, 
        mount_config: [
          {
            efs_name: gateway_efs,
            mount_path: /home/ubuntu/efs/gateway_ws
          },
          {
            efs_name: model_efs,
            mount_path: /mnt/efs/model_ws
          },
          {
            efs_name: data_efs,
            mount_path: /mnt/efs/data_ws
          },
        ]
      },
      {
        class: downloader, # dns onlt access to vpc subnet, access to outnet
        name: downloader,
        type: t2.xlarge,
        num: 1,
        ami_id: ami-0b0ea68c435eb488d, 
        mount_config: [
          {
            efs_name: gateway_efs,
            mount_path: /home/ubuntu/efs/gateway_ws
          },
          {
            efs_name: data_efs,
            mount_path: /mnt/efs/data_ws
          },
        ]
      },
  ]


#============== gateway config ==============
authorized_user:
  [
    {
      name: xxx,
      mac_address: xxxxx,
      mac_user: xxxx,
      mac_id: xxxx,
    },  
    # {
    #   name: xxx,
    #   mac_address: ,
    #   mac_user: ,
    #   mac_id: ,
    # },
  ]

#============== batch config ==============
output_config:  /home/ubuntu/.cluster/cluster.config
