job_name: job1

# =================== resource config ===================
cpu_num: 16
memory_size: 16 # M or G?

# =================== container config ===================
image_name:  qinjielin/python3.6:v0.2
entry_cmd: ["python", "test.py"]
vcpu_num: 1
mount_config: [
  {
    efs_name: code_efs,
    efs_path: /config/,
    container_path: /usr/local/python_ws/results,
  },
]  #only support one efs mount